#!/bin/bash

# A simple shell script to run the ImageTerrier Basic Indexer tool
#
# @author Jonathon Hare

bin=`dirname "$0"`

java -Xshare:off -Xmx6G -Djava.awt.headless=true -Dimageterrier.log.level=debug -XX:-UseGCOverheadLimit -Dbundle.size=1000 -Dmemory.reserved=400000000 -cp "$bin/target/ImageTerrierTools-3.5-SNAPSHOT-jar-with-dependencies.jar" org.imageterrier.basictools.BasicIndexer ${1+"$@"}
